apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: acme.webshop.android.app
  title: ACME Shop android app
spec:
  system: acme.webshop
  owner: mobile
  type: app
  lifecycle: experimental
  consumesApi:
    - acme.webshop.account.api
    - acme.webshop.inventory.api
    - acme.webshop.sale.api
    - acme.webshop.shipping.api
  dependsOn:
    - acme.webshop.account.service
    - acme.webshop.inventory.service
    - acme.webshop.sale.service
    - acme.webshop.shipping.service
    - acme.webshop.apigw
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: acme.webshop.ios.app
  title: ACME Shop iOS app
spec:
  owner: mobile
  type: app
  lifecycle: production
    consumesApi:
    - acme.webshop.account.api
    - acme.webshop.inventory.api
    - acme.webshop.sale.api
    - acme.webshop.shipping.api
  dependsOn:
    - acme.webshop.account.service
    - acme.webshop.inventory.service
    - acme.webshop.sale.service
    - acme.webshop.shipping.service
    - acme.webshop.apigw