apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: acme.webshop.inventory.service
  title: ACME Shop inventory service
spec:
  system: acme.webshop.inventory
  type: service
  owner: backend
  lifecycle: production
  providesApi: acme.webshop.inventory.api
  dependsOn:
    - acme.webshop.inventory.db