apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: dev
  title: Development

spec:
  type: business-unit
  parent: acmecorp
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: dev.mobile
  title: Dev Mobile Team
spec:
  type: team
  parent: dev
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: dev.frontend
  title: Dev Frontend Team
spec:
  type: team
  parent: dev
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: dev.backend
  title: Dev Backend Team
spec:
  type: team
  parent: dev
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: brad.pitt
spec:
  profile:
    displayName: Brad Pitt
    email: brad.pitt@acme.corp
    picture: https://m.media-amazon.com/images/M/MV5BMjA1MjE2MTQ2MV5BMl5BanBnXkFtZTcwMjE5MDY0Nw@@._V1_UX214_CR0,0,214,317_AL_.jpg
  memberOf: [dev.mobile]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ed.kross
spec:
  profile:
    displayName: Ed Kross
    email: ed.kross@acme.corp
    picture: https://m.media-amazon.com/images/M/MV5BMjA1MjE2MTQ2MV5BMl5BanBnXkFtZTcwMjE5MDY0Nw@@._V1_UX214_CR0,0,214,317_AL_.jpg
  memberOf: [dev.backend]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: julia.roberts
spec:
  profile:
    displayName: Julia Roberts
    email: julia.roberts@acme.corp
    picture: https://m.media-amazon.com/images/M/MV5BMTQzNjU3MDczN15BMl5BanBnXkFtZTYwNzY2Njc4._V1_UX214_CR0,0,214,317_AL_.jpg
  memberOf: [dev.frontend]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: don.tiffany
spec:
  profile:
    displayName: Don Tiffany
    email: don.tiffany@acme.corp
    picture: https://m.media-amazon.com/images/M/MV5BMTg5ODk2MDM1Ml5BMl5BanBnXkFtZTcwNjQ1OTkyMQ@@._V1_UY317_CR16,0,214,317_AL_.jpg
  memberOf: [dev.backend]
