apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: acmecorp
  title: ACME corp
spec:
  type: organization
  parent: acme
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: teams
spec:
  targets:
    - ./teams/dev/catalog-info.yaml
    - ./teams/operations/catalog-info.yaml
    - ./domains/webshop/catalog-info.yaml
