apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: webshop
spec:
  owner: dev-team
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: systems
spec:
  targets:
    - ./systems/webshop.yaml
    - ./systems/account.yaml
    - ./systems/inventory.yaml
    - ./systems/sale.yaml
    - ./systems/shipping.yaml
